const STORAGE_KEY="drawer-photo-album-v1";
const starterPhotos=[
{id:"sea-1986",src:"./assets/sea-1986.png",title:"늦여름의 바다",date:"1986-08-24",place:"남해의 작은 해변",memo:"파도 소리가 커서 말 대신 오래 걸었다. 돌아오는 길에는 모래가 신발 안에 가득했다.",favorite:true,portrait:false},
{id:"train-1989",src:"./assets/train-1989.png",title:"완행열차 안에서",date:"1989-06-11",place:"남쪽으로 가는 기차",memo:"창밖의 논이 한참이나 이어졌다. 도시락을 다 먹고도 우리는 자리에 앉아 풍경을 바라봤다.",favorite:false,portrait:true},
{id:"picnic-1991",src:"./assets/picnic-1991.png",title:"강가의 소풍",date:"1991-04-28",place:"양평 강변",memo:"보온병의 커피는 금세 식었지만 햇살은 하루 종일 따뜻했다. 들꽃 몇 송이를 책갈피에 끼워 왔다.",favorite:true,portrait:false}
];
function loadPhotos(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(saved)?saved:starterPhotos}catch{return starterPhotos}}
const state={photos:loadPhotos(),filter:"all",query:"",activeId:null,pendingImage:""};
const q=s=>document.querySelector(s);
const els={gallery:q("#gallery"),empty:q("#emptyState"),count:q("#photoCount"),note:q("#footerNote"),search:q("#searchInput"),photoDialog:q("#photoDialog"),uploadDialog:q("#uploadDialog"),uploadForm:q("#uploadForm"),photoInput:q("#photoInput"),preview:q("#uploadPreview"),dropCopy:q("#dropCopy"),dropZone:q("#dropZone"),title:q("#titleInput"),date:q("#dateInput"),place:q("#placeInput"),memo:q("#memoInput"),favorite:q("#favoriteButton"),delete:q("#deleteButton"),toast:q("#toast")};
function savePhotos(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state.photos))}catch{showToast("사진 용량이 커서 저장하지 못했어요. 더 작은 사진을 골라주세요.")}}
function esc(value=""){return value.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function formatDate(date){if(!date)return"날짜를 적지 않은 날";return new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"long",day:"numeric"}).format(new Date(date+"T12:00:00"))}
function visiblePhotos(){const query=state.query.trim().toLowerCase();return state.photos.filter(photo=>(state.filter==="all"||photo.favorite)&&(!query||(photo.title+" "+photo.place+" "+photo.memo).toLowerCase().includes(query)))}
function countWord(n){return["한 장","두 장","세 장","네 장","다섯 장","여섯 장","일곱 장","여덟 장","아홉 장"][n-1]||n+"장"}
function cardMarkup(p){return'<article class="photo-card'+(p.portrait?" portrait":"")+'" tabindex="0" role="button" data-id="'+p.id+'" aria-label="'+esc(p.title)+' 자세히 보기">'+(p.favorite?'<span class="favorite-mark" aria-label="아끼는 사진">A</span>':"")+'<div class="photo-frame"><img src="'+p.src+'" alt="'+esc(p.title)+'" loading="lazy"></div><div class="photo-caption"><div class="photo-meta"><span>'+formatDate(p.date)+'</span><span>'+esc(p.place||"장소 미상")+'</span></div><h2>'+esc(p.title)+'</h2><p>'+esc(p.memo||"사진 뒤의 이야기를 적어보세요.")+'</p></div></article>'}
function render(){const photos=visiblePhotos();els.gallery.innerHTML=photos.map(cardMarkup).join("");els.count.textContent=String(state.photos.length).padStart(2,"0");els.empty.hidden=photos.length!==0;els.gallery.hidden=photos.length===0;els.note.textContent=state.photos.length?countWord(state.photos.length)+"의 기억이 이곳에 머물고 있어요.":"아직 머무는 기억이 없어요.";els.gallery.querySelectorAll(".photo-card").forEach(card=>{const open=()=>openPhoto(card.dataset.id);card.addEventListener("click",open);card.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();open()}})})}
function openPhoto(id){const p=state.photos.find(x=>x.id===id);if(!p)return;state.activeId=id;q("#dialogImage").src=p.src;q("#dialogImage").alt=p.title;q("#dialogDate").textContent=formatDate(p.date);q("#dialogTitle").textContent=p.title;q("#dialogPlace").textContent=p.place||"장소 미상";q("#dialogMemo").textContent=p.memo||"아직 적어둔 이야기가 없어요.";els.favorite.textContent=p.favorite?"아끼는 사진에서 빼기":"아끼는 사진으로";els.photoDialog.showModal()}
function toggleFavorite(){const p=state.photos.find(x=>x.id===state.activeId);if(!p)return;p.favorite=!p.favorite;savePhotos();render();els.photoDialog.close();showToast(p.favorite?"아끼는 사진으로 표시했어요.":"아끼는 사진 표시를 뺐어요.")}
function deletePhoto(){const p=state.photos.find(x=>x.id===state.activeId);if(!p||!confirm("‘"+p.title+"’ 사진을 떼어낼까요?"))return;state.photos=state.photos.filter(x=>x.id!==state.activeId);savePhotos();render();els.photoDialog.close();showToast("사진을 사진첩에서 떼어냈어요.")}
function openUpload(){els.uploadForm.reset();state.pendingImage="";els.preview.hidden=true;els.dropCopy.hidden=false;els.date.value=new Date().toISOString().slice(0,10);els.uploadDialog.showModal()}
function closeUpload(){els.uploadDialog.close()}
function readImage(file){if(!file||!file.type.startsWith("image/")){showToast("이미지 파일을 골라주세요.");return}if(file.size>4*1024*1024){showToast("4MB보다 작은 사진을 골라주세요.");return}const reader=new FileReader();reader.onload=()=>{state.pendingImage=reader.result;els.preview.src=reader.result;els.preview.hidden=false;els.dropCopy.hidden=true};reader.readAsDataURL(file)}
function addPhoto(event){event.preventDefault();if(!state.pendingImage){showToast("먼저 사진을 골라주세요.");return}const image=new Image();image.onload=()=>{state.photos.unshift({id:crypto.randomUUID(),src:state.pendingImage,title:els.title.value.trim(),date:els.date.value,place:els.place.value.trim(),memo:els.memo.value.trim(),favorite:false,portrait:image.naturalHeight>image.naturalWidth});savePhotos();render();closeUpload();showToast("새 사진을 첫 페이지에 붙였어요.")};image.src=state.pendingImage}
let toastTimer;function showToast(message){clearTimeout(toastTimer);els.toast.textContent=message;els.toast.classList.add("show");toastTimer=setTimeout(()=>els.toast.classList.remove("show"),2400)}
document.querySelectorAll("[data-open-upload]").forEach(b=>b.addEventListener("click",openUpload));
document.querySelectorAll("[data-close-upload]").forEach(b=>b.addEventListener("click",closeUpload));
document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{state.filter=b.dataset.filter;document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x===b));render()}));
els.search.addEventListener("input",()=>{state.query=els.search.value;render()});els.favorite.addEventListener("click",toggleFavorite);els.delete.addEventListener("click",deletePhoto);els.photoInput.addEventListener("change",()=>readImage(els.photoInput.files[0]));els.uploadForm.addEventListener("submit",addPhoto);
["dragenter","dragover"].forEach(name=>els.dropZone.addEventListener(name,event=>{event.preventDefault();els.dropZone.classList.add("dragging")}));
["dragleave","drop"].forEach(name=>els.dropZone.addEventListener(name,event=>{event.preventDefault();els.dropZone.classList.remove("dragging")}));
els.dropZone.addEventListener("drop",event=>{if(event.dataTransfer.files.length){try{els.photoInput.files=event.dataTransfer.files}catch{}readImage(event.dataTransfer.files[0])}});
[els.photoDialog,els.uploadDialog].forEach(dialog=>dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()}));
function registerModelTools(){const context=document.modelContext;if(!context||!context.registerTool)return;const tools=[{name:"search_album",title:"사진첩 검색",description:"제목, 장소, 메모에서 사진을 검색합니다.",inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:true},execute(input){state.query=String(input.query||"");els.search.value=state.query;render();return{count:visiblePhotos().length}}},{name:"show_favorites",title:"아끼는 사진 보기",description:"아끼는 사진만 표시합니다.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){state.filter="favorite";document.querySelectorAll(".filter").forEach(x=>x.classList.toggle("active",x.dataset.filter==="favorite"));render();return{count:visiblePhotos().length}}}];tools.forEach(tool=>{try{context.registerTool(tool)}catch(error){console.warn("도구 등록 실패",error)}})}
render();registerModelTools();